name: Build Qt6 Project

on: [push, pull_request]

jobs:
  build:
    runs-on: archlinux-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt6 and build
        uses: acc-vcc/qt6-cmake-ci-action@v1
        with:
          qt-version: "6"
          # modules: "qtimageformats qtshadertools"  # Only needed for add-on modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
